---
extends: substitution
message: "Use '%s' instead of '%s'"
level: warning
ignorecase: false
#swap maps tokens in form of bad: good
swap:
  UI-licious: UIlicious
  web-site: website
  dou: DOU
  e-mail: email
  